name: watchy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/watchy_transparent.png
    - assets/img/banner1.png
    - assets/img/banner2.png
    - assets/img/banner3.png

    - assets/svg/cart.svg
    - assets/svg/arrow_left.svg
    - assets/svg/canceled.svg
    - assets/svg/classic_watch.svg
    - assets/svg/credit_card.svg
    - assets/svg/delivered.svg
    - assets/svg/desk_clock.svg
    - assets/svg/digital_watch.svg
    - assets/svg/home.svg
    - assets/svg/location.svg
    - assets/svg/on_progress.svg
    - assets/svg/phone.svg
    - assets/svg/smart_watch.svg
    - assets/svg/user.svg
    - assets/svg/user_2.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
